cv24/urls.py
from django.urls import path
from . import views

app_name = "cv24"

urlpatterns = [
    path("", views.detect_edges, name="edges"),
    path("edges/", views.detect_edges, name="edges"),
    path("ocr/", views.perform_ocr, name="ocr"),
    path("deblur/", views.deblur_image, name="deblur"),
]

cvp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("cv24.urls")),
    path("management/", admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cv24/models.py
from django.db import models

# Create your models here.

cv24/views.py
from django.shortcuts import render
from django.http import HttpRequest
from cv24.edges import EdgeDetector
from cv24.ocr import OCR
from cv24.deblur import Deblur24
from time import sleep
from os.path import dirname, abspath, join as pjoin


def detect_edges(request: HttpRequest):
    if request.method == "POST":
        image = request.FILES.get("image")
        min_val = int(request.POST.get("min_val"))
        max_val = int(request.POST.get("max_val"))
        detector = EdgeDetector()
        output = detector.apply_canny(image, minval=min_val, maxval=max_val)
        original = detector.enc_im_to_b64(image)
        context = {"original": original, "output": output}
        return render(request, "cv24/edge.html", context)

    context = {}
    return render(request, "cv24/edge.html", context)


def perform_ocr(request: HttpRequest):
    if request.method == "POST":
        image = request.FILES.get("image")
        ocr = OCR()
        output, text = ocr.apply_ocr(image)
        original = ocr.enc_im_to_b64(image)
        context = {"original": original, "output": output, "text": text}
        return render(request, "cv24/ocr.html", context)

    context = {}
    return render(request, "cv24/ocr.html", context)


def deblur_image(request: HttpRequest):
    if request.method == "POST":
        image = request.FILES.get("image")
        bname = image.name.split("_")[0]
        sname = f"{bname}_sharp.png"
        simage = pjoin(dirname(dirname(abspath(__file__))), sname)

        deblur = Deblur24()
        original = deblur.enc_im_to_b64(image)
        output = deblur.enc_im_to_b64(simage)
        context = {"original": original, "output": output}
        return render(request, "cv24/deblur.html", context)

    context = {}
    return render(request, "cv24/deblur.html", context)

canny/templates/canny/detect_edge.html
{% extends 'canny/base.html' %}

{% block title %}Edge Detectiton using Canny Edge Dectector{% endblock title %}

{% block content %}
<div class="upl-form-wrp">
    <form action="{% url 'canny:detect-edges' %}" method="POST" class="upl-frm"
        enctype="multipart/form-data">
        {% csrf_token %}
        <label for="image" class="f-lab">Image</label>
        <input type="file" name="image" accept=".png, .jpg" required
            class="inp">
        <button type="submit" class="btn">Detect Edges</button>
    </form>
</div>
<div class="org-res-wrp">
    <div class="org-res left ">
        <h3>Input Image</h3>
        <img
            src="{{ original }}" alt>
    </div>
    <div class="org-res">
        <h3>Output Image</h3>
        <img
            src="{{ output }}" alt>
    </div>
</div>
{% endblock content %}

cv24/templates/cv24/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'cv24/css/main.css' %}">
        <title>{% block title %}{% endblock title %}</title>
    </head>
    <body class="body-content">
        {% include 'cv24/navbar.html' %}
        {% block content %}{% endblock content %}
    </body>
</html>

cv24/templates/cv24/deblur.html
{% extends 'cv24/base.html' %}

{% block title %}
CV24 - Image Deblurring
{% endblock title %}

{% block content %}
<div class="upl-form-wrp">
    <form action="{% url 'cv24:deblur' %}" method="POST" class="upl-frm"
        enctype="multipart/form-data">
        {% csrf_token %}
        <label for="image" class="f-lab">Image</label>
        <input type="file" name="image" accept=".png, .jpg" required
            class="inp">
        <button type="submit" class="btn">Deblur Image</button>
    </form>
</div>
{% if original %}
<div class="org-res-wrp">
    <div class="org-res left ">
        <h3>Input Image</h3>
        <img src="{{ original }}" alt>
    </div>
    <div class="org-res">
        <h3>Deblurred Image</h3>
        <img src="{{ output }}" alt>
    </div>
</div>
{% endif %}
{% endblock content %}

cv24/templates/cv24/edge.html
{% extends 'cv24/base.html' %}

{% block title %}
CV24 - Edge Detectiton using Canny Edge Dectector
{% endblock title %}

{% block content %}
<div class="upl-form-wrp">
    <form action="{% url 'cv24:edges' %}" method="POST" class="upl-frm"
        enctype="multipart/form-data">
        {% csrf_token %}
        <label for="image" class="f-lab">Image</label>
        <input type="file" name="image" accept=".png, .jpg" required
            class="inp">
        <button type="submit" class="btn">Detect Edges</button>
        <div class="f-extra">
            <label for="min_val" class="f-lab">
                <small>Lower Threshold</small>
            </label>
            <input type="number" value="100" min="50" max="500"
                name="min_val">
            <label for="max_val" class="ml-4r">
                <small>Upper Threshold</small>
            </label>
            <input type="number" value="200" min="50" max="500"
                name="max_val">
        </div>
    </form>
</div>
{% if original %}
<div class="org-res-wrp">
    <div class="org-res left ">
        <h3>Input Image</h3>
        <img
            src="{{ original }}" alt>
    </div>
    <div class="org-res">
        <h3>Output Image</h3>
        <img
            src="{{ output }}" alt>
    </div>
</div>
{% endif %}
{% endblock content %}

cv24/templates/cv24/navbar.html
{% load static %}

<div class="navigation">
    <a href="#" class="no-style-lnk">
        <div class="nav-br-wrp">
            <div class="nav-lg-it">C</div>
            <div class="nav-lg-it">V</div>
            <div class="nav-lg-it">2</div>
            <div class="nav-lg-it">4</div>
        </div>
    </a>
    <div class="nav-it-wrp">
        <a href="{% url 'cv24:edges' %}"
            class="nav-it no-style-lnk">
            Edge Detection
        </a>
        <a href="{% url 'cv24:ocr' %}"
            class="nav-it no-style-lnk">
            Optical Character Recognition
        </a>
        <a href="{% url 'cv24:deblur' %}"
            class="nav-it no-style-lnk">
            Image Deblurring
        </a>
    </div>
</div>

cv24/templates/cv24/ocr.html
{% extends 'cv24/base.html' %}

{% block title %}
CV24 - Optical Character Recognition
{% endblock title %}

{% block content %}
<div class="upl-form-wrp">
    <form action="{% url 'cv24:ocr' %}" method="POST" class="upl-frm"
        enctype="multipart/form-data">
        {% csrf_token %}
        <label for="image" class="f-lab">Image</label>
        <input type="file" name="image" accept=".png, .jpg" required
            class="inp">
        <button type="submit" class="btn">Perform OCR</button>
    </form>
</div>

{% if original %}
<div class="org-res-wrp">
    <div class="org-res left ">
        <h3>Input Image</h3>
        <img
            src="{{ original }}" alt>
    </div>
    <div class="org-res">
        <h3>Output Image</h3>
        <img
            src="{{ output }}" alt>
    </div>
</div>
<div class="ocr-txt-wrp">
    <h3><u>Recognized Texts</u></h3>
    {% if text %}
    <p>{{text|linebreaksbr|safe}}</p>
    {% else %}
    <p class="no-txt">No text recognized in uploaded image !</p>
    {% endif %}
</div>
{% endif %}
{% endblock content %}